language: node_js
node_js:
  - "5"
services:
    - mysql
env:
  - CXX=g++-4.8

before_install:
- mysql -e "create database IF NOT EXISTS test;" -uroot
- npm install -g grunt-cli
- export USERNAME=root
- sudo bash -c 'bash <(wget -qO- https://raw.githubusercontent.com/tjanczuk/edge/master/tools/debian_ubuntu_clean_install.sh)'
install: npm install