language: node_js
node_js:
  - "5"
services:
    - mysql
env:
  - CXX=g++-4.8
mono:
  - latest
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
- mysql -e "create database IF NOT EXISTS test;" -uroot
- npm install -g grunt-cli

install:
  - export USERNAME=root
  - sudo bash -c 'bash <(wget -qO- https://raw.githubusercontent.com/tjanczuk/edge/master/tools/debian_ubuntu_clean_install.sh)'
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo apt-get update
  - sudo apt-get install mono-devel
  - npm install -g grunt-cli
  - npm install edge
  - npm install
